[project]
name = "Agent-Quant"
version = "0.1.0"
description = "Get data, build prompt, LLM agent trading signal, simulated trading"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "granian[dotenv,pname,uvloop]>=2.5.6",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "sqlmodel>=0.0.27",
    "loguru>=0.7.3",
    "fastapi-users[oauth,sqlalchemy]>=15.0.1",
    "asyncpg>=0.30.0",
    "longport>=3.0.17",
    "ta-lib>=0.6.8",
    "pandas>=2.3.3",
    "pydantic-ai-slim[openai]>=1.10.0",
    "quantstats>=0.0.77",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.2.0",
    "pytest>=8.4.2",
    "ruff>=0.14.3",
    "alembic>=1.17.1",
    "aiosqlite>=0.21.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.7",
]


[tool.ruff]
exclude = ["alembic"]
line-length = 100
preview = true
fix = true
unsafe-fixes = true

[tool.ruff.lint]
future-annotations = true
select = ["F", "E", "UP", "B", "SIM", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"

[tool.uv.workspace]
members = ["git"]
